/**
 * Map a full-size /images/cards/ image URL to its ~760px thumbnail in
 * /images/cards/thumbs/.
 *
 * The card image files are hero-sized (1400-1600px) because the same file
 * doubles as the full-bleed hero on each detail page. The card grids show them
 * at ~320-456px, so they should load the thumbnail, not the hero. Detail-page
 * heroes keep passing the full-size src. Thumbnails are generated by
 * scripts/gen-card-thumbs.mjs (re-run it after adding or changing a card image).
 */
export function cardThumb(src) {
  return typeof src === 'string'
    && src.includes('/images/cards/')
    && !src.includes('/thumbs/')
    ? src.replace('/images/cards/', '/images/cards/thumbs/')
    : src;
}
