/**
 * sync-nav.mjs
 *
 * Generates src/data/navData.js from the source-of-truth data files.
 * Run automatically before every build via the "prebuild" npm script.
 * Also available manually: npm run sync-nav
 *
 * navData.js exports three slim datasets used by components that load
 * on EVERY page (Header, SiteFooter, ExpeditionExplorer). Keeping these
 * separate from the full data files prevents ~400 KB of itinerary/description
 * text from being bundled into the initial page load.
 *
 * ┌─────────────────┬──────────────────────────────────────────────────────┐
 * │ Export          │ Used by                                              │
 * ├─────────────────┼──────────────────────────────────────────────────────┤
 * │ NAV_EXPS        │ Header (mega menu + search)                          │
 * │ CARD_EXPS       │ ExpeditionExplorer (homepage cards)                  │
 * │ NAV_ISRAEL      │ Header (Israel sub-menu) + SiteFooter                │
 * └─────────────────┴──────────────────────────────────────────────────────┘
 *
 * To add a field to a slim dataset, add it to the relevant FIELDS array
 * below and re-run the script (or just run `npm run build`).
 */

import fs   from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT      = path.resolve(__dirname, '..');

/* ── Import source data ─────────────────────────────────────────────────── */
const { EXPS }         = await import(path.join(ROOT, 'src/data/mockData.js'));
const { ISRAEL_TRIPS } = await import(path.join(ROOT, 'src/data/israelData.js'));

/* ── Field lists — add fields here if new components need them ───────────
   Keep these minimal: every field adds to the initial JS download.        */

/** Fields needed by Header mega-menu and search bar */
const NAV_EXP_FIELDS = [
  'id', 'slug', 'name', 'nameHe', 'nameEn',
  'country', 'countryHe', 'elev', 'type', 'typeHe',
];

/** Fields needed by ExpeditionExplorer cards on the homepage */
const CARD_EXP_FIELDS = [
  'id', 'slug', 'name', 'nameHe', 'nameEn',
  'country', 'countryHe', 'flag', 'img', 'grad',
  'soldOut', 'elevNum', 'type', 'typeHe', 'diff', 'diffHe',
  'price', 'priceStr', 'continent', 'airtableEvents', 'groupCapacity',
];

/** Fields needed for Israel trips in Header sub-menu */
const NAV_ISRAEL_FIELDS = [
  'slug', 'name', 'nameEn', 'live',
];

/* ── Build slim datasets ────────────────────────────────────────────────── */
function pick(obj, fields) {
  return Object.fromEntries(fields.filter(f => f in obj).map(f => [f, obj[f]]));
}

const navExps    = EXPS.map(e => pick(e, NAV_EXP_FIELDS));
const cardExps   = EXPS.map(e => pick(e, CARD_EXP_FIELDS));
const navIsrael  = ISRAEL_TRIPS.map(t => pick(t, NAV_ISRAEL_FIELDS));

/* ── Write output ───────────────────────────────────────────────────────── */
const output = `/**
 * navData.js — AUTO-GENERATED by scripts/sync-nav.mjs
 * DO NOT EDIT MANUALLY — run \`npm run sync-nav\` or \`npm run build\`.
 *
 * Slim datasets for components loaded on every page.
 * Full data lives in mockData.js / israelData.js.
 */

/* eslint-disable */
// prettier-ignore
export const NAV_EXPS = ${JSON.stringify(navExps, null, 2)};

// prettier-ignore
export const CARD_EXPS = ${JSON.stringify(cardExps, null, 2)};

// prettier-ignore
export const NAV_ISRAEL = ${JSON.stringify(navIsrael, null, 2)};
`;

const outPath = path.join(ROOT, 'src/data/navData.js');
fs.writeFileSync(outPath, output, 'utf8');

/* ── Summary ────────────────────────────────────────────────────────────── */
const kb = s => (Buffer.byteLength(s, 'utf8') / 1024).toFixed(1) + ' KB';
console.log('✅  navData.js synced');
console.log(`    NAV_EXPS   : ${navExps.length} expeditions  (${kb(JSON.stringify(navExps))})`);
console.log(`    CARD_EXPS  : ${cardExps.length} expeditions  (${kb(JSON.stringify(cardExps))})`);
console.log(`    NAV_ISRAEL : ${navIsrael.length} trips        (${kb(JSON.stringify(navIsrael))})`);
